### ISSUE TITLE
Twitter profile picture fetch not working

### ISSUE THREAD

**Issue by JuanRdBO** [cardinal-labs/cardinal-identity-ui#17]
Hello! When I'm trying to get the Twitter profile picture URL from the identity sdk, I get "internal server error". Are there any fixes for that?

**Comment by gchatz22** [comment]
Hey we haven't noticed + haven't had reported such an issue recently. Do you mind sharing some detail on how you are experiencing this issue? Is it at https://twitter.cardinal.so/ or some other dApp that has integrated our identity sdk

**Comment by jpbogle** [comment]
@JuanRdBO were you able to get this resolved?

**Comment by JuanRdBO** [comment]
Hey there! Yes, it works now. Sorry to not have responded. I just now saw it :-)
