### ISSUE TITLE
TypeError: fields must be array of Layout instances

### ISSUE THREAD

**Issue by 0xPratik** [cardinal-labs/cardinal-identity-ui#22]
I just imported this and i get error :- 

  <WalletIdentityProvider identities={[IDENTITIES["twitter"]]}>
      <Component {...pageProps} />
    </WalletIdentityProvider>

<img width="1079" alt="Screenshot 2022-10-27 at 9 00 24 PM" src="https://user-images.githubusercontent.com/62953475/198329461-2779ab3a-f8c5-42ca-b079-ce7199c1834e.png">

**Comment by gchatz22** [comment]
hey could delete `node_modules` and try version `v4.1.24` of `namespace-components`?

**Comment by 0xPratik** [comment]
Same Error

**Comment by 0xPratik** [comment]
Tested with 2 Projects and getting the same error

**Comment by jpbogle** [comment]
can you check in yarn.lock if @solana/buffer-layout is included? it should be a hard dependency on the newest version

**Comment by gchatz22** [comment]
issue resolved offline by updating to current latest version `v4.1.27`
